INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES ( 'admin', '{bcrypt}$2a$10$et7t/56FULw.WohTI9fIpuu2G78xPUxhWGNAnrymZ6fchFRX0Nd1q', true);
INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES ( 'manoj', '{bcrypt}$2a$10$VT/n8x/VMzrBeoS6wW02g.a34ldNbb.HR2ZpS9oVff6lEyH33m9i6', true);


INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ( 'admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES(USERNAME, AUTHORITY) VALUES ( 'manoj', 'ROLE_USER');

